In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%cd -q ..

In [53]:
import lcdb
import lcpfn 
import torch as th
from functools import partial
import numpy as np
from matplotlib import pyplot as plt

In [5]:
curve = lcdb.get_curve(3, "sklearn.linear_model.LogisticRegression")

In [39]:
anchors, scores_train, scores_valid, scores_test = curve
print(anchors)
print(scores_train)
print(scores_valid)
print(scores_test)

[16, 23, 32, 45, 64, 91, 128, 181, 256, 362, 512, 724, 1024, 1448, 2048, 2588]
[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9375, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9375, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9375, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9375, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9375, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.913, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9565, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9565, 1.0, 1.0, 1.0, 1.0, 0.9565, 1.0, 1.0, 1.0, 1.0, 0.9565, 0.9565, 

In [64]:
def dummyLoader(batch_size = None, seq_len = None, num_features = None, hyperparameters = None, single_eval_pos = None, x = None, y = None, z = None):
    anchors, scores_train, scores_valid, scores_test = curve
    x = th.Tensor(anchors, )
    y = th.mean(th.Tensor(scores_train), dim = 1)
    y_new = th.mean(th.Tensor(scores_test), dim = 1)
    return x, y, y_new

x, y ,z = dummyLoader(curve)
print(x)
print(y)
print(z)

tensor([  16.,   23.,   32.,   45.,   64.,   91.,  128.,  181.,  256.,  362.,
         512.,  724., 1024., 1448., 2048., 2588.])
tensor([0.9975, 0.9951, 0.9920, 0.9876, 0.9829, 0.9782, 0.9768, 0.9719, 0.9682,
        0.9664, 0.9666, 0.9666, 0.9662, 0.9666, 0.9676, 0.9684])
tensor([0.6607, 0.7168, 0.7664, 0.8081, 0.8513, 0.8825, 0.9076, 0.9294, 0.9431,
        0.9517, 0.9574, 0.9606, 0.9628, 0.9651, 0.9673, 0.9686])
tensor(0.9662)


In [62]:
get_batch_func = partial(dummyLoader, x = anchors, y = scores_train, z = scores_test)

In [63]:
result = lcpfn.train_lcpfn(get_batch_func=get_batch_func, 
                          seq_len=16,
                         emsize=256,
                         nlayers=3,
                         num_borders=1000,
                         lr=0.001,
                         batch_size=1,
                         epochs=3)

Using 0 y evals to estimate 1000 buckets. Cut off the last 0 ys.


RuntimeError: min(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.